### ISSUE TITLE
Baseline models

### ISSUE THREAD

**Issue by juliagusak** [mil-tokyo/bc_learning_sound#5]
Hello!

Is it possible to find somewhere  baseline models mentioned in the paper (SoundNet5, M18, Logmel-Cnn, Logmel-Cnn + BN) and implemented with Chainer? Thanks!

**Comment by Tokozume** [comment]
Hello, I'm so sorry for the late reply. 

We do not know if there are Chainer implementations of these networks. You can add the training of SoundNet5 or M18 by implementing models/[network_name].py, editing models/__init__.py, and editing opts.py. Logmel-CNN is a little bit difficult to implement because it requires the calculation of log-mel features. Thank you.

**Comment by juliagusak** [comment]
Thank you for the answer!
